database: d should be db

(PyFlask) C:\Users\woodrur\Desktop\Dojo\Week 4\flask_mysql>python server.py
Traceback (most recent call last):
  File "server.py", line 6, in <module>
    mysql = MySQLConnector(app, 'mydb')
  File "C:\Users\woodrur\Desktop\Dojo\Week 4\flask_mysql\mysqlconnection.py", line 40, in MySQLConnector
    return MySQLConnection(app, db)
  File "C:\Users\woodrur\Desktop\Dojo\Week 4\flask_mysql\mysqlconnection.py", line 9, in __init__
    'database': d, # we got db as an argument
NameError: global name 'd' is not defined

No username:

sqlalchemy.exc.OperationalError: (_mysql_exceptions.OperationalError) (1045, "Access denied for user 'ODBC'@'localhost' (using password: YES)")

Wrong Password:
sqlalchemy.exc.OperationalError: (_mysql_exceptions.OperationalError) (1045, "Access denied for user 'root'@'localhost' (using password: NO)")

Wrong Port:

sqlalchemy.exc.OperationalError: (_mysql_exceptions.OperationalError) (2003, "Can't connect to MySQL server on '127.0.0.1' (10061)")